apiVersion: v1
kind: Service
metadata:
  name: journal-api-service
  labels:
    app: journal-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:744763865781:certificate/e369c746-3e71-4940-8aea-44ed50ba44c1"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

spec:
  type: LoadBalancer

  selector:
    app: journal-api

  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000