mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib

presets:
  logsCollection:
    enabled: true

  kubernetesAttributes:
    enabled: true

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 400

    batch: {}

  exporters:
    # Send traces to Tempo
    otlp/tempo:
      endpoint: tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true

    # Send logs to Loki using Loki's native OTLP endpoint
    otlphttp/loki:
      endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp

    debug:
      verbosity: basic

  service:
    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - otlp/tempo
          - debug

      logs:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - otlphttp/loki
          - debug

service:
  enabled: true